// Comprehensive Scholarship Database
const scholarshipsDatabase = [
    // USA Scholarships
    {
        id: 1,
        title: "Fulbright Foreign Student Program",
        country: "USA",
        university: "Various US Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "October 2024",
        funding: "Fully Funded",
        description: "Provides grants for graduate study, research, and teaching in the United States",
        benefits: ["Full tuition", "Living stipend", "Health insurance", "Airfare"],
        link: "https://foreign.fulbrightonline.org/",
        eligibility: "International students with bachelor's degree"
    },
    {
        id: 2,
        title: "AAUW International Fellowships",
        country: "USA",
        university: "Various US Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "December 2024",
        funding: "Fully Funded",
        description: "Awards for women pursuing full-time graduate or postdoctoral study in the United States",
        benefits: ["$18,000-$30,000 stipend", "Research support"],
        link: "https://www.aauw.org/resources/programs/fellowships-grants/current-opportunities/international/",
        eligibility: "Women who are not US citizens"
    },
    {
        id: 3,
        title: "Stanford Knight-Hennessy Scholars",
        country: "USA",
        university: "Stanford University",
        level: "Masters",
        field: "All Fields",
        deadline: "October 2024",
        funding: "Fully Funded",
        description: "Fully funded scholarship for graduate study at Stanford",
        benefits: ["Full tuition", "Stipend", "Travel", "Leadership development"],
        link: "https://knight-hennessy.stanford.edu/",
        eligibility: "All international students"
    },
    {
        id: 4,
        title: "Clark University Global Scholars",
        country: "USA",
        university: "Clark University",
        level: "Undergraduate",
        field: "All Fields",
        deadline: "January 2025",
        funding: "Fully Funded",
        description: "Full tuition scholarship for international undergraduates",
        benefits: ["Full tuition", "$2,500 annual stipend"],
        link: "https://www.clarku.edu/offices/admissions/scholarships-and-aid/",
        eligibility: "High-achieving international students"
    },

    // UK Scholarships
    {
        id: 5,
        title: "Chevening Scholarships",
        country: "UK",
        university: "Various UK Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "November 2024",
        funding: "Fully Funded",
        description: "UK government's international scholarship programme",
        benefits: ["Full tuition", "Living allowance", "Return airfare", "Arrival allowance"],
        link: "https://www.chevening.org/",
        eligibility: "Minimum 2 years work experience"
    },
    {
        id: 6,
        title: "Commonwealth Scholarships",
        country: "UK",
        university: "Various UK Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "December 2024",
        funding: "Fully Funded",
        description: "For students from low and middle-income Commonwealth countries",
        benefits: ["Full tuition", "Living expenses", "Return airfare"],
        link: "https://cscuk.fcdo.gov.uk/scholarships/",
        eligibility: "Commonwealth citizens"
    },
    {
        id: 7,
        title: "Gates Cambridge Scholarships",
        country: "UK",
        university: "University of Cambridge",
        level: "PhD",
        field: "All Fields",
        deadline: "October 2024",
        funding: "Fully Funded",
        description: "Prestigious scholarship for international postgraduate students",
        benefits: ["Full tuition", "Maintenance allowance", "Airfare", "Family allowance"],
        link: "https://www.gatescambridge.org/",
        eligibility: "Non-UK citizens applying for postgraduate study"
    },
    {
        id: 8,
        title: "Rhodes Scholarships",
        country: "UK",
        university: "University of Oxford",
        level: "Masters",
        field: "All Fields",
        deadline: "September 2024",
        funding: "Fully Funded",
        description: "One of the world's most prestigious international scholarship programmes",
        benefits: ["Full tuition", "Living stipend", "Travel expenses"],
        link: "https://www.rhodeshouse.ox.ac.uk/",
        eligibility: "Outstanding students aged 18-28"
    },

    // Canada Scholarships
    {
        id: 9,
        title: "Vanier Canada Graduate Scholarships",
        country: "Canada",
        university: "Various Canadian Universities",
        level: "PhD",
        field: "All Fields",
        deadline: "November 2024",
        funding: "Fully Funded",
        description: "For doctoral students demonstrating leadership skills",
        benefits: ["$50,000 per year for 3 years"],
        link: "https://vanier.gc.ca/",
        eligibility: "Nominated by Canadian universities"
    },
    {
        id: 10,
        title: "University of Toronto Ontario Graduate Scholarship",
        country: "Canada",
        university: "University of Toronto",
        level: "Masters",
        field: "All Fields",
        deadline: "Varies",
        funding: "Fully Funded",
        description: "Merit-based scholarship for graduate students",
        benefits: ["$15,000 minimum per year"],
        link: "https://www.sgs.utoronto.ca/awards/ontario-graduate-scholarship/",
        eligibility: "Graduate students at UofT"
    },
    {
        id: 11,
        title: "University of British Columbia International Leader of Tomorrow Award",
        country: "Canada",
        university: "University of British Columbia",
        level: "Undergraduate",
        field: "All Fields",
        deadline: "December 2024",
        funding: "Fully Funded",
        description: "For exceptional international students with financial need",
        benefits: ["Full financial need coverage"],
        link: "https://you.ubc.ca/financial-planning/scholarships-awards-international-students/",
        eligibility: "International students with leadership potential"
    },

    // Australia Scholarships
    {
        id: 12,
        title: "Australia Awards Scholarships",
        country: "Australia",
        university: "Various Australian Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "April 2025",
        funding: "Fully Funded",
        description: "Long-term development awards for study in Australia",
        benefits: ["Full tuition", "Living expenses", "Airfare", "Health insurance"],
        link: "https://www.dfat.gov.au/people-to-people/australia-awards/",
        eligibility: "Citizens of eligible countries"
    },
    {
        id: 13,
        title: "University of Melbourne Graduate Research Scholarships",
        country: "Australia",
        university: "University of Melbourne",
        level: "PhD",
        field: "All Fields",
        deadline: "October 2024",
        funding: "Fully Funded",
        description: "For international students undertaking graduate research",
        benefits: ["Living allowance", "Relocation grant", "Thesis allowance"],
        link: "https://scholarships.unimelb.edu.au/",
        eligibility: "International research students"
    },
    {
        id: 14,
        title: "Monash University International Merit Scholarship",
        country: "Australia",
        university: "Monash University",
        level: "Undergraduate",
        field: "All Fields",
        deadline: "Varies",
        funding: "Partially Funded",
        description: "For high-achieving international students",
        benefits: ["$10,000 per year"],
        link: "https://www.monash.edu/study/fees-scholarships/scholarships",
        eligibility: "International students with excellent academics"
    },

    // Germany Scholarships
    {
        id: 15,
        title: "DAAD Scholarships",
        country: "Germany",
        university: "Various German Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "November 2024",
        funding: "Fully Funded",
        description: "German Academic Exchange Service scholarships",
        benefits: ["Monthly stipend", "Health insurance", "Travel allowance"],
        link: "https://www.daad.de/en/",
        eligibility: "International students with bachelor's degree"
    },
    {
        id: 16,
        title: "Heinrich Böll Foundation Scholarships",
        country: "Germany",
        university: "Various German Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "March 2025",
        funding: "Fully Funded",
        description: "For international students committed to sustainability",
        benefits: ["€850 monthly", "€300 book allowance"],
        link: "https://www.boell.de/en/foundation/application",
        eligibility: "Students with social commitment"
    },
    {
        id: 17,
        title: "Konrad-Adenauer-Stiftung Scholarships",
        country: "Germany",
        university: "Various German Universities",
        level: "PhD",
        field: "All Fields",
        deadline: "July 2024",
        funding: "Fully Funded",
        description: "For international doctoral students",
        benefits: ["€1,350 monthly", "Family allowance", "Health insurance"],
        link: "https://www.kas.de/en/web/begabtenfoerderung-und-kultur/scholarship-programs",
        eligibility: "Doctoral students with Christian democratic values"
    },

    // Netherlands Scholarships
    {
        id: 18,
        title: "Holland Scholarship",
        country: "Netherlands",
        university: "Various Dutch Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "May 2025",
        funding: "Partially Funded",
        description: "For non-EEA international students",
        benefits: ["€5,000 one-time grant"],
        link: "https://www.studyinholland.nl/finances/holland-scholarship",
        eligibility: "Non-EEA students"
    },
    {
        id: 19,
        title: "Orange Tulip Scholarship",
        country: "Netherlands",
        university: "Various Dutch Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "April 2025",
        funding: "Partially Funded",
        description: "For students from specific countries",
        benefits: ["€3,000-€24,000"],
        link: "https://www.nesorussia.org/scholarships/orange-tulip-scholarship",
        eligibility: "Students from Brazil, China, India, Indonesia, Mexico, Russia, South Korea, Thailand, Vietnam"
    },
    {
        id: 20,
        title: "University of Amsterdam Excellence Scholarships",
        country: "Netherlands",
        university: "University of Amsterdam",
        level: "Masters",
        field: "All Fields",
        deadline: "January 2025",
        funding: "Fully Funded",
        description: "For exceptionally talented students",
        benefits: ["€25,000", "Full tuition waiver"],
        link: "https://www.uva.nl/en/education/masters/scholarships-tuition/scholarships-and-loans/amsterdam-excellence-scholarship/amsterdam-excellence-scholarship.html",
        eligibility: "Non-EU students with excellent academic record"
    },

    // Sweden Scholarships
    {
        id: 21,
        title: "Swedish Institute Scholarships for Global Professionals",
        country: "Sweden",
        university: "Various Swedish Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "February 2025",
        funding: "Fully Funded",
        description: "For students from eligible countries",
        benefits: ["Full tuition", "Living expenses", "Travel grant", "Insurance"],
        link: "https://si.se/en/apply/scholarships/swedish-institute-scholarships-for-global-professionals/",
        eligibility: "Citizens of eligible countries with work experience"
    },
    {
        id: 22,
        title: "Lund University Global Scholarship",
        country: "Sweden",
        university: "Lund University",
        level: "Masters",
        field: "All Fields",
        deadline: "January 2025",
        funding: "Fully Funded",
        description: "For top academic international students",
        benefits: ["Full or partial tuition waiver"],
        link: "https://www.lunduniversity.lu.se/admissions/scholarships-and-funding",
        eligibility: "Non-EU/EEA students with excellent grades"
    },

    // Norway Scholarships
    {
        id: 23,
        title: "Norwegian Government Quota Scheme",
        country: "Norway",
        university: "Various Norwegian Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "December 2024",
        funding: "Fully Funded",
        description: "For students from developing countries",
        benefits: ["Full tuition", "Living expenses", "Travel costs"],
        link: "https://www.nokut.no/en/norwegian-education/the-quota-scheme/",
        eligibility: "Citizens of eligible developing countries"
    },
    {
        id: 24,
        title: "University of Oslo International Summer School Scholarships",
        country: "Norway",
        university: "University of Oslo",
        level: "Undergraduate",
        field: "All Fields",
        deadline: "March 2025",
        funding: "Partially Funded",
        description: "For summer school programs",
        benefits: ["Tuition waiver"],
        link: "https://www.uio.no/english/studies/summerschool/",
        eligibility: "International students"
    },

    // France Scholarships
    {
        id: 25,
        title: "Eiffel Excellence Scholarship",
        country: "France",
        university: "Various French Universities",
        level: "Masters",
        field: "Engineering",
        deadline: "January 2025",
        funding: "Fully Funded",
        description: "For top international students in engineering, law, economics",
        benefits: ["€1,181 monthly for Masters", "€1,700 for PhD"],
        link: "https://www.campusfrance.org/en/eiffel-scholarship-program-of-excellence",
        eligibility: "International students under 30 (Masters) or 35 (PhD)"
    },
    {
        id: 26,
        title: "École Normale Supérieure International Selection",
        country: "France",
        university: "École Normale Supérieure",
        level: "Masters",
        field: "Sciences",
        deadline: "December 2024",
        funding: "Fully Funded",
        description: "For outstanding international students",
        benefits: ["€1,000 monthly for 3 years"],
        link: "https://www.ens.psl.eu/",
        eligibility: "Top international students in sciences"
    },

    // Switzerland Scholarships
    {
        id: 27,
        title: "Swiss Government Excellence Scholarships",
        country: "Switzerland",
        university: "Various Swiss Universities",
        level: "PhD",
        field: "All Fields",
        deadline: "November 2024",
        funding: "Fully Funded",
        description: "For foreign scholars in research and arts",
        benefits: ["CHF 1,920 monthly", "Health insurance", "Housing allowance"],
        link: "https://www.sbfi.admin.ch/sbfi/en/home/education/scholarships-and-grants/swiss-government-excellence-scholarships.html",
        eligibility: "Postgraduate researchers and artists"
    },
    {
        id: 28,
        title: "ETH Zurich Excellence Scholarship",
        country: "Switzerland",
        university: "ETH Zurich",
        level: "Masters",
        field: "Engineering",
        deadline: "December 2024",
        funding: "Partially Funded",
        description: "For top international Masters students",
        benefits: ["CHF 11,000 per semester + tuition waiver"],
        link: "https://ethz.ch/students/en/studies/financial/scholarships/excellencescholarship.html",
        eligibility: "Outstanding international students"
    },

    // Japan Scholarships
    {
        id: 29,
        title: "MEXT Scholarships",
        country: "Japan",
        university: "Various Japanese Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "May 2025",
        funding: "Fully Funded",
        description: "Japanese government scholarship for international students",
        benefits: ["Monthly stipend", "Tuition waiver", "Airfare"],
        link: "https://www.studyinjapan.go.jp/en/planning/scholarship/",
        eligibility: "International students"
    },

    // South Korea Scholarships
    {
        id: 30,
        title: "Korean Government Scholarship Program (KGSP)",
        country: "South Korea",
        university: "Various Korean Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "March 2025",
        funding: "Fully Funded",
        description: "For international students to study in Korea",
        benefits: ["Full tuition", "Living allowance", "Airfare", "Korean language training"],
        link: "https://www.studyinkorea.go.kr/en/sub/gks/allnew_invite.do",
        eligibility: "International students under 40"
    },

    // China Scholarships
    {
        id: 31,
        title: "Chinese Government Scholarship",
        country: "China",
        university: "Various Chinese Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "March 2025",
        funding: "Fully Funded",
        description: "For international students in China",
        benefits: ["Full tuition", "Accommodation", "Monthly stipend"],
        link: "http://www.csc.edu.cn/",
        eligibility: "International students"
    },

    // New Zealand Scholarships
    {
        id: 32,
        title: "New Zealand Scholarships",
        country: "New Zealand",
        university: "Various NZ Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "July 2024",
        funding: "Fully Funded",
        description: "For students from developing countries",
        benefits: ["Full tuition", "Living costs", "Travel", "Health insurance"],
        link: "https://www.mfat.govt.nz/en/aid-and-development/scholarships/",
        eligibility: "Citizens of eligible developing countries"
    },

    // Additional USA Scholarships
    {
        id: 33,
        title: "Yale University Scholarships",
        country: "USA",
        university: "Yale University",
        level: "Undergraduate",
        field: "All Fields",
        deadline: "January 2025",
        funding: "Fully Funded",
        description: "Need-based financial aid for international students",
        benefits: ["Full demonstrated need"],
        link: "https://admissions.yale.edu/financial-aid-prospective-students",
        eligibility: "Admitted international students with financial need"
    },
    {
        id: 34,
        title: "Harvard University Scholarships",
        country: "USA",
        university: "Harvard University",
        level: "Undergraduate",
        field: "All Fields",
        deadline: "January 2025",
        funding: "Fully Funded",
        description: "Need-blind admission for all students",
        benefits: ["100% of demonstrated need"],
        link: "https://college.harvard.edu/financial-aid",
        eligibility: "All admitted students"
    },
    {
        id: 35,
        title: "MIT Need-Based Financial Aid",
        country: "USA",
        university: "MIT",
        level: "Undergraduate",
        field: "Engineering",
        deadline: "February 2025",
        funding: "Fully Funded",
        description: "Need-blind admission for international students",
        benefits: ["Full demonstrated need"],
        link: "https://sfs.mit.edu/",
        eligibility: "Admitted international students"
    },

    // Additional UK Scholarships
    {
        id: 36,
        title: "Imperial College London President's PhD Scholarships",
        country: "UK",
        university: "Imperial College London",
        level: "PhD",
        field: "Sciences",
        deadline: "November 2024",
        funding: "Fully Funded",
        description: "For outstanding PhD candidates",
        benefits: ["Full tuition", "Annual stipend"],
        link: "https://www.imperial.ac.uk/study/pg/fees-and-funding/scholarships/",
        eligibility: "International PhD applicants"
    },
    {
        id: 37,
        title: "University of Edinburgh Global Research Scholarship",
        country: "UK",
        university: "University of Edinburgh",
        level: "PhD",
        field: "All Fields",
        deadline: "February 2025",
        funding: "Fully Funded",
        description: "For exceptional research students",
        benefits: ["Full tuition difference between home and overseas fees"],
        link: "https://www.ed.ac.uk/student-funding/postgraduate/international/global/research",
        eligibility: "International PhD students"
    },

    // Additional Canadian Scholarships
    {
        id: 38,
        title: "Lester B. Pearson International Scholarship",
        country: "Canada",
        university: "University of Toronto",
        level: "Undergraduate",
        field: "All Fields",
        deadline: "November 2024",
        funding: "Fully Funded",
        description: "For exceptional international students",
        benefits: ["Full tuition", "Books", "Incidental fees", "Residence for 4 years"],
        link: "https://future.utoronto.ca/pearson/",
        eligibility: "International students nominated by their school"
    },
    {
        id: 39,
        title: "McGill University Entrance Scholarships",
        country: "Canada",
        university: "McGill University",
        level: "Undergraduate",
        field: "All Fields",
        deadline: "January 2025",
        funding: "Partially Funded",
        description: "For top incoming students",
        benefits: ["$3,000-$10,000"],
        link: "https://www.mcgill.ca/studentaid/scholarships-aid/future-undergraduates",
        eligibility: "High-achieving students"
    },

    // Additional European Scholarships
    {
        id: 40,
        title: "Erasmus Mundus Joint Masters",
        country: "Various",
        university: "Multiple European Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "Varies",
        funding: "Fully Funded",
        description: "Study in multiple European countries",
        benefits: ["Full tuition", "Living allowance", "Travel costs"],
        link: "https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en",
        eligibility: "International students"
    },

    // Additional Scholarships for Various Countries
    {
        id: 41,
        title: "Joint Japan World Bank Graduate Scholarship",
        country: "Various",
        university: "Partner Universities Worldwide",
        level: "Masters",
        field: "Development",
        deadline: "March 2025",
        funding: "Fully Funded",
        description: "For students from developing countries",
        benefits: ["Full tuition", "Living expenses", "Travel", "Health insurance"],
        link: "https://www.worldbank.org/en/programs/scholarships",
        eligibility: "Citizens of World Bank member developing countries"
    },
    {
        id: 42,
        title: "ADB-Japan Scholarship Program",
        country: "Various",
        university: "ADB Partner Universities",
        level: "Masters",
        field: "Economics",
        deadline: "Varies",
        funding: "Fully Funded",
        description: "For students from ADB member countries",
        benefits: ["Full tuition", "Living expenses", "Books", "Travel"],
        link: "https://www.adb.org/work-with-us/careers/japan-scholarship-program",
        eligibility: "Citizens of ADB member countries"
    },

    // Additional Scholarships
    {
        id: 43,
        title: "Rotary Peace Fellowships",
        country: "Various",
        university: "Rotary Peace Centers",
        level: "Masters",
        field: "Peace Studies",
        deadline: "May 2025",
        funding: "Fully Funded",
        description: "For peace and conflict resolution studies",
        benefits: ["Full tuition", "Room and board", "Transportation"],
        link: "https://www.rotary.org/en/our-programs/peace-fellowships",
        eligibility: "Professionals committed to peace"
    },
    {
        id: 44,
        title: "Aga Khan Foundation International Scholarship",
        country: "Various",
        university: "Various Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "March 2025",
        funding: "Partially Funded",
        description: "For students from developing countries",
        benefits: ["50% grant, 50% loan"],
        link: "https://www.akdn.org/our-agencies/aga-khan-foundation/international-scholarship-programme",
        eligibility: "Students from select developing countries with no other funding"
    },
    {
        id: 45,
        title: "Google Lime Scholarship",
        country: "USA",
        university: "Various US Universities",
        level: "Undergraduate",
        field: "Computer Science",
        deadline: "December 2024",
        funding: "Partially Funded",
        description: "For students with disabilities studying computer science",
        benefits: ["$10,000 (US) or $5,000 (Canada)"],
        link: "https://buildyourfuture.withgoogle.com/scholarships/google-lime-scholarship",
        eligibility: "Students with disabilities in CS"
    },
    {
        id: 46,
        title: "Generation Google Scholarship",
        country: "Various",
        university: "Various Universities",
        level: "Undergraduate",
        field: "Computer Science",
        deadline: "December 2024",
        funding: "Partially Funded",
        description: "For students in computer science",
        benefits: ["$10,000 (US) or €7,000 (Europe)"],
        link: "https://buildyourfuture.withgoogle.com/scholarships/generation-google-scholarship",
        eligibility: "CS students from underrepresented groups"
    },
    {
        id: 47,
        title: "Hubert H. Humphrey Fellowship Program",
        country: "USA",
        university: "Various US Universities",
        level: "Postdoctoral",
        field: "All Fields",
        deadline: "October 2024",
        funding: "Fully Funded",
        description: "For experienced professionals from eligible countries",
        benefits: ["Tuition", "Living allowance", "Travel", "Professional development"],
        link: "https://www.humphreyfellowship.org/",
        eligibility: "Mid-career professionals with leadership potential"
    },
    {
        id: 48,
        title: "Australia National University Chancellor's International Scholarship",
        country: "Australia",
        university: "Australian National University",
        level: "Undergraduate",
        field: "All Fields",
        deadline: "December 2024",
        funding: "Partially Funded",
        description: "For high-achieving international students",
        benefits: ["$10,000-$25,000 per year"],
        link: "https://www.anu.edu.au/study/scholarships",
        eligibility: "International students with excellent academic record"
    },
    {
        id: 49,
        title: "University of Queensland International Scholarships",
        country: "Australia",
        university: "University of Queensland",
        level: "Masters",
        field: "All Fields",
        deadline: "November 2024",
        funding: "Partially Funded",
        description: "For international students with excellent academic record",
        benefits: ["25-100% tuition waiver"],
        link: "https://scholarships.uq.edu.au/",
        eligibility: "High-achieving international students"
    },
    {
        id: 50,
        title: "Denmark Government Scholarships",
        country: "Denmark",
        university: "Various Danish Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "March 2025",
        funding: "Fully Funded",
        description: "For non-EU/EEA students",
        benefits: ["Full or partial tuition waiver + monthly stipend"],
        link: "https://studyindenmark.dk/",
        eligibility: "Non-EU/EEA students"
    },
    
    // NEW SCHOLARSHIPS FOR 2025-2027 - ONGOING APPLICATIONS
    
    // UK Scholarships 2025-2027
    {
        id: 51,
        title: "Chevening Scholarships 2026-2027",
        country: "UK",
        university: "Various UK Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "October 2025",
        funding: "Fully Funded",
        description: "UK government's flagship scholarship program for future leaders to pursue one-year master's degrees",
        benefits: ["Full tuition fees", "Monthly living allowance", "Return airfare", "Arrival allowance", "Visa costs"],
        link: "https://www.chevening.org/",
        eligibility: "Minimum 2 years work experience, bachelor's degree holders"
    },
    {
        id: 52,
        title: "Commonwealth Scholarships 2026-2027",
        country: "UK",
        university: "Various UK Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "December 2025",
        funding: "Fully Funded",
        description: "For students from low and middle-income Commonwealth countries to study in the UK",
        benefits: ["Full tuition", "Living expenses", "Return airfare", "Thesis grant", "Warm clothing allowance"],
        link: "https://cscuk.fcdo.gov.uk/scholarships/",
        eligibility: "Commonwealth citizens, cannot afford UK studies without scholarship"
    },
    {
        id: 53,
        title: "Oxford Pershing Square Scholarship 2026-2027",
        country: "UK",
        university: "University of Oxford",
        level: "Masters",
        field: "All Fields",
        deadline: "January 2026",
        funding: "Fully Funded",
        description: "Full-funding for 1+1 MBA program or selected master's programs at Oxford",
        benefits: ["Full tuition fees", "£20,780 annual living expenses", "Two years of study support"],
        link: "https://www.pssp.ox.ac.uk/",
        eligibility: "Outstanding leadership potential, commitment to positive change"
    },
    {
        id: 54,
        title: "Reach Oxford Scholarships 2026",
        country: "UK",
        university: "University of Oxford",
        level: "Undergraduate",
        field: "All Fields",
        deadline: "January 2026",
        funding: "Fully Funded",
        description: "For students from developing countries who cannot study for a degree in their own country",
        benefits: ["Full tuition", "Living costs grant", "One return airfare per year"],
        link: "https://www.ox.ac.uk/admissions/undergraduate/fees-and-funding/oxford-support/reach-oxford-scholarship",
        eligibility: "From low-income countries, ordinarily resident in country"
    },

    // Germany Scholarships 2025-2027
    {
        id: 55,
        title: "DAAD EPOS Scholarships 2026-2027",
        country: "Germany",
        university: "Various German Universities",
        level: "Masters",
        field: "Engineering",
        deadline: "September 2025",
        funding: "Fully Funded",
        description: "Development-Related Postgraduate Courses scholarships for professionals from developing countries",
        benefits: ["€934 monthly stipend", "Health insurance", "Travel allowance", "Study allowance"],
        link: "https://www.daad.de/en/study-and-research-in-germany/scholarships/epos/",
        eligibility: "Minimum 2 years work experience, bachelor's degree"
    },
    {
        id: 56,
        title: "DAAD Helmut Schmidt Programme 2026",
        country: "Germany",
        university: "Various German Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "October 2025",
        funding: "Fully Funded",
        description: "Master's scholarships for future leaders from developing countries with public policy focus",
        benefits: ["€934 monthly allowance", "Health insurance", "Travel costs", "Study materials"],
        link: "https://www.daad.de/en/",
        eligibility: "Bachelor's degree, work experience, from developing countries"
    },
    {
        id: 57,
        title: "Deutschland Stipendium 2025-2026",
        country: "Germany",
        university: "Various German Universities",
        level: "Undergraduate",
        field: "All Fields",
        deadline: "Varies by University",
        funding: "Partially Funded",
        description: "Merit-based scholarship for talented students studying at German universities",
        benefits: ["€300 per month for at least 2 semesters"],
        link: "https://www.deutschlandstipendium.de/",
        eligibility: "Outstanding academic performance, social engagement"
    },
    {
        id: 58,
        title: "Konrad-Adenauer-Stiftung Scholarships 2026",
        country: "Germany",
        university: "Various German Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "January 2026",
        funding: "Fully Funded",
        description: "For international students committed to democracy and social justice",
        benefits: ["€934 monthly", "Health insurance", "Family allowance", "Book money"],
        link: "https://www.kas.de/en/web/begabtenfoerderung-und-kultur/scholarship-programs",
        eligibility: "Above-average academic performance, social commitment"
    },

    // USA Scholarships 2025-2027
    {
        id: 59,
        title: "Fulbright Foreign Student Program 2026-2027",
        country: "USA",
        university: "Various US Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "October 2025",
        funding: "Fully Funded",
        description: "Prestigious US government scholarship for graduate study in the United States",
        benefits: ["Full tuition", "Living stipend", "Health insurance", "Round-trip airfare"],
        link: "https://foreign.fulbrightonline.org/",
        eligibility: "Bachelor's degree, strong academic record, leadership potential"
    },
    {
        id: 60,
        title: "Rotary Peace Fellowship 2026-2027",
        country: "USA",
        university: "Various Universities",
        level: "Masters",
        field: "Social Sciences",
        deadline: "May 2026",
        funding: "Fully Funded",
        description: "For leaders committed to peace and conflict prevention and resolution",
        benefits: ["Full tuition and fees", "Room and board", "Round-trip transportation", "Internship/field study funding"],
        link: "https://www.rotary.org/en/our-programs/peace-fellowships",
        eligibility: "Work experience in peace and development, proficiency in English"
    },
    {
        id: 61,
        title: "AAUW International Fellowships 2026-2027",
        country: "USA",
        university: "Various US Universities",
        level: "PhD",
        field: "All Fields",
        deadline: "December 2025",
        funding: "Fully Funded",
        description: "For women pursuing full-time graduate or postdoctoral study in the United States",
        benefits: ["$20,000-$50,000 fellowship", "Research support"],
        link: "https://www.aauw.org/resources/programs/fellowships-grants/current-opportunities/international/",
        eligibility: "Women who are not US citizens or permanent residents"
    },
    {
        id: 62,
        title: "Yale World Fellows Program 2026",
        country: "USA",
        university: "Yale University",
        level: "Postdoctoral",
        field: "All Fields",
        deadline: "November 2025",
        funding: "Fully Funded",
        description: "Four-month leadership development program for emerging global leaders",
        benefits: ["Full living stipend", "Travel costs", "Health insurance", "Leadership training"],
        link: "https://worldfellows.yale.edu/",
        eligibility: "Mid-career professionals, demonstrated leadership"
    },

    // Australia Scholarships 2025-2027
    {
        id: 63,
        title: "Australia Awards Scholarships 2026-2027",
        country: "Australia",
        university: "Various Australian Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "April 2026",
        funding: "Fully Funded",
        description: "Long-term development awards for study in Australia for students from developing countries",
        benefits: ["Full tuition", "Living allowance", "Return airfare", "Establishment allowance", "Health insurance"],
        link: "https://www.dfat.gov.au/people-to-people/australia-awards/",
        eligibility: "Citizens of eligible developing countries"
    },
    {
        id: 64,
        title: "University of Sydney International Scholarship 2026",
        country: "Australia",
        university: "University of Sydney",
        level: "Masters",
        field: "All Fields",
        deadline: "January 2026",
        funding: "Fully Funded",
        description: "Merit-based scholarships for outstanding international students",
        benefits: ["Full tuition fee waiver", "Annual living allowance $35,000"],
        link: "https://www.sydney.edu.au/scholarships/",
        eligibility: "Academic excellence, applying to eligible programs"
    },
    {
        id: 65,
        title: "Monash Graduate Excellence Scholarship 2026",
        country: "Australia",
        university: "Monash University",
        level: "Masters",
        field: "All Fields",
        deadline: "December 2025",
        funding: "Fully Funded",
        description: "For high-achieving international students pursuing graduate coursework",
        benefits: ["Full or partial tuition fee waiver"],
        link: "https://www.monash.edu/study/fees-scholarships/scholarships",
        eligibility: "Strong academic performance, international students"
    },

    // Canada Scholarships 2025-2027
    {
        id: 66,
        title: "Vanier Canada Graduate Scholarships 2026",
        country: "Canada",
        university: "Various Canadian Universities",
        level: "PhD",
        field: "All Fields",
        deadline: "November 2025",
        funding: "Fully Funded",
        description: "For doctoral students who demonstrate leadership skills and high scholarly achievement",
        benefits: ["$50,000 per year for 3 years"],
        link: "https://vanier.gc.ca/",
        eligibility: "Nominated by Canadian institutions, doctoral students"
    },
    {
        id: 67,
        title: "Lester B. Pearson International Scholarship 2026",
        country: "Canada",
        university: "University of Toronto",
        level: "Undergraduate",
        field: "All Fields",
        deadline: "November 2025",
        funding: "Fully Funded",
        description: "Recognizes international students who demonstrate exceptional academic achievement and creativity",
        benefits: ["Full tuition for 4 years", "Books and incidental fees", "Full residence support"],
        link: "https://future.utoronto.ca/pearson/",
        eligibility: "Nominated by schools, exceptional leadership"
    },
    {
        id: 68,
        title: "University of British Columbia International Scholar Award 2026",
        country: "Canada",
        university: "University of British Columbia",
        level: "Undergraduate",
        field: "All Fields",
        deadline: "December 2025",
        funding: "Partially Funded",
        description: "For exceptional international students entering first year",
        benefits: ["Up to $10,000 renewable award"],
        link: "https://you.ubc.ca/financial-planning/scholarships-awards-international-students/",
        eligibility: "Outstanding academic and personal profile"
    },

    // France Scholarships 2025-2027
    {
        id: 69,
        title: "Eiffel Excellence Scholarship Programme 2026-2027",
        country: "France",
        university: "Various French Universities",
        level: "Masters",
        field: "Engineering",
        deadline: "January 2026",
        funding: "Fully Funded",
        description: "French government scholarship for international students in engineering, science, economics and law",
        benefits: ["€1,400 monthly allowance", "Travel expenses", "Health insurance", "Cultural activities"],
        link: "https://www.campusfrance.org/en/eiffel-scholarship-program-of-excellence",
        eligibility: "Students under 30 years (Masters) or 35 (PhD)"
    },
    {
        id: 70,
        title: "Emile Boutmy Scholarships 2026",
        country: "France",
        university: "Sciences Po Paris",
        level: "Masters",
        field: "Social Sciences",
        deadline: "December 2025",
        funding: "Partially Funded",
        description: "For outstanding international students from outside EU applying to Sciences Po",
        benefits: ["€5,000 to €19,000 tuition waiver", "Living expenses possible"],
        link: "https://www.sciencespo.fr/admissions/en/financing/emile-boutmy-scholarship",
        eligibility: "Non-EU students, academic excellence"
    },

    // Netherlands Scholarships 2025-2027
    {
        id: 71,
        title: "Holland Scholarship 2026-2027",
        country: "Netherlands",
        university: "Various Dutch Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "February 2026",
        funding: "Partially Funded",
        description: "For international students from outside EEA studying in the Netherlands",
        benefits: ["€5,000 one-time payment"],
        link: "https://www.studyinholland.nl/finances/holland-scholarship",
        eligibility: "Non-EEA nationality, first-time students in Netherlands"
    },
    {
        id: 72,
        title: "Orange Knowledge Programme 2026",
        country: "Netherlands",
        university: "Various Dutch Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "April 2026",
        funding: "Fully Funded",
        description: "For professionals from selected countries to study short courses or master's programs",
        benefits: ["Full tuition", "Living allowance", "Travel costs", "Insurance"],
        link: "https://www.studyinholland.nl/finances/orange-knowledge-programme",
        eligibility: "From OKP eligible countries, relevant work experience"
    },

    // Sweden Scholarships 2025-2027
    {
        id: 73,
        title: "Swedish Institute Scholarships for Global Professionals 2026",
        country: "Sweden",
        university: "Various Swedish Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "February 2026",
        funding: "Fully Funded",
        description: "For highly qualified students seeking to make a positive impact on society",
        benefits: ["Full tuition fees", "SEK 10,000/month living expenses", "Travel grant", "Insurance"],
        link: "https://si.se/en/apply/scholarships/swedish-institute-scholarships-for-global-professionals/",
        eligibility: "Minimum 3,000 hours of work experience"
    },
    {
        id: 74,
        title: "Lund University Global Scholarship 2026",
        country: "Sweden",
        university: "Lund University",
        level: "Masters",
        field: "All Fields",
        deadline: "January 2026",
        funding: "Partially Funded",
        description: "Merit-based scholarships for outstanding students from outside EU/EEA",
        benefits: ["25%, 50%, 75% or 100% tuition fee waiver"],
        link: "https://www.lunduniversity.lu.se/admissions/scholarships",
        eligibility: "Academic excellence, non-EU/EEA students"
    },

    // Switzerland Scholarships 2025-2027
    {
        id: 75,
        title: "ETH Zurich Excellence Masters Scholarships 2026",
        country: "Switzerland",
        university: "ETH Zurich",
        level: "Masters",
        field: "Engineering",
        deadline: "December 2025",
        funding: "Fully Funded",
        description: "Merit-based scholarships for outstanding students pursuing Masters at ETH Zurich",
        benefits: ["CHF 12,000 per semester", "Full tuition waiver"],
        link: "https://ethz.ch/en/studies/financial/scholarships.html",
        eligibility: "Excellent academic record, enrolled in ETH Master's program"
    },
    {
        id: 76,
        title: "Swiss Government Excellence Scholarships 2026-2027",
        country: "Switzerland",
        university: "Various Swiss Universities",
        level: "PhD",
        field: "All Fields",
        deadline: "December 2025",
        funding: "Fully Funded",
        description: "For international students and researchers to pursue doctoral or postdoctoral research",
        benefits: ["CHF 1,920 monthly", "Health insurance", "Travel allowance", "Housing allowance"],
        link: "https://www.sbfi.admin.ch/sbfi/en/home/education/scholarships-and-grants/swiss-government-excellence-scholarships.html",
        eligibility: "Master's degree, research proposal"
    },

    // Japan Scholarships 2025-2027
    {
        id: 77,
        title: "MEXT Japanese Government Scholarship 2026-2027",
        country: "Japan",
        university: "Various Japanese Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "May 2026",
        funding: "Fully Funded",
        description: "Japanese government scholarship for international students to study in Japan",
        benefits: ["Full tuition", "¥144,000 monthly stipend", "Airfare", "Japanese language course"],
        link: "https://www.studyinjapan.go.jp/en/planning/scholarship/",
        eligibility: "Bachelor's degree holders under 35 years"
    },
    {
        id: 78,
        title: "University of Tokyo Fellowship 2026",
        country: "Japan",
        university: "University of Tokyo",
        level: "PhD",
        field: "All Fields",
        deadline: "November 2025",
        funding: "Fully Funded",
        description: "For outstanding doctoral students at the University of Tokyo",
        benefits: ["¥200,000 monthly stipend", "Tuition exemption"],
        link: "https://www.u-tokyo.ac.jp/en/",
        eligibility: "Admitted to UTokyo doctoral program, academic excellence"
    },

    // South Korea Scholarships 2025-2027
    {
        id: 79,
        title: "Korean Government Scholarship Program (KGSP) 2026",
        country: "South Korea",
        university: "Various Korean Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "March 2026",
        funding: "Fully Funded",
        description: "South Korean government scholarship for international students",
        benefits: ["Full tuition", "900,000 KRW monthly", "Airfare", "Korean language training", "Medical insurance"],
        link: "https://www.studyinkorea.go.kr/en/sub/gks/allnew_invite.do",
        eligibility: "Bachelor's degree holders under 40 years"
    },
    {
        id: 80,
        title: "KAIST International Student Scholarship 2026",
        country: "South Korea",
        university: "KAIST",
        level: "Masters",
        field: "Engineering",
        deadline: "Ongoing",
        funding: "Fully Funded",
        description: "For outstanding international students in STEM fields at KAIST",
        benefits: ["Full tuition", "Monthly allowance", "Research support"],
        link: "https://admission.kaist.ac.kr/",
        eligibility: "Strong academic record in STEM"
    },

    // China Scholarships 2025-2027
    {
        id: 81,
        title: "Chinese Government Scholarship - CSC 2026",
        country: "China",
        university: "Various Chinese Universities",
        level: "PhD",
        field: "All Fields",
        deadline: "April 2026",
        funding: "Fully Funded",
        description: "Scholarship program for international students to study in China at doctoral level",
        benefits: ["Full tuition waiver", "3,500 RMB monthly stipend", "Accommodation allowance", "Medical insurance"],
        link: "https://www.campuschina.org/",
        eligibility: "Master's degree holders under 40 years"
    },
    {
        id: 82,
        title: "Tsinghua University Schwarzman Scholars 2026",
        country: "China",
        university: "Tsinghua University",
        level: "Masters",
        field: "All Fields",
        deadline: "September 2025",
        funding: "Fully Funded",
        description: "One-year master's program for future global leaders",
        benefits: ["Full tuition", "Stipend", "Travel costs", "Room and board"],
        link: "https://www.schwarzmanscholars.org/",
        eligibility: "Leadership potential, bachelor's degree"
    },

    // New Zealand Scholarships 2025-2027
    {
        id: 83,
        title: "New Zealand Development Scholarships 2026",
        country: "New Zealand",
        university: "Various NZ Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "June 2026",
        funding: "Fully Funded",
        description: "For students from developing countries to study in New Zealand",
        benefits: ["Full tuition", "NZ$491/week living allowance", "Travel costs", "Health insurance"],
        link: "https://www.mfat.govt.nz/en/aid-and-development/scholarships/",
        eligibility: "Citizens of eligible developing countries"
    },
    {
        id: 84,
        title: "University of Auckland International Doctoral Scholarship 2026",
        country: "New Zealand",
        university: "University of Auckland",
        level: "PhD",
        field: "All Fields",
        deadline: "November 2025",
        funding: "Fully Funded",
        description: "For international students undertaking doctoral research",
        benefits: ["Full tuition", "NZ$30,000 annual stipend"],
        link: "https://www.auckland.ac.nz/en/study/scholarships-and-awards.html",
        eligibility: "Admitted to PhD program, research excellence"
    },

    // Norway Scholarships 2025-2027
    {
        id: 85,
        title: "Norwegian Government Quota Scheme 2026",
        country: "Norway",
        university: "Various Norwegian Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "December 2025",
        funding: "Fully Funded",
        description: "For students from developing countries and countries in transition",
        benefits: ["Living expenses grant", "Tuition covered", "Travel allowance"],
        link: "https://www.uio.no/english/studies/admission/quota-scheme/",
        eligibility: "From selected developing countries"
    },

    // Belgium Scholarships 2025-2027
    {
        id: 86,
        title: "VLIR-UOS Scholarships 2026-2027",
        country: "Belgium",
        university: "Various Belgian Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "February 2026",
        funding: "Fully Funded",
        description: "For students from selected developing countries to study in Flanders",
        benefits: ["Full tuition", "Monthly allowance", "Accommodation", "Travel costs", "Insurance"],
        link: "https://www.vliruos.be/en/scholarships",
        eligibility: "From eligible developing countries, work experience preferred"
    },

    // Italy Scholarships 2025-2027
    {
        id: 87,
        title: "Italian Government Scholarships 2026-2027",
        country: "Italy",
        university: "Various Italian Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "May 2026",
        funding: "Partially Funded",
        description: "For international students to study and conduct research in Italy",
        benefits: ["€900 monthly allowance", "Health insurance"],
        link: "https://studyinitaly.esteri.it/",
        eligibility: "International students, academic merit"
    },

    // Ireland Scholarships 2025-2027
    {
        id: 88,
        title: "Government of Ireland International Education Scholarships 2026",
        country: "Ireland",
        university: "Various Irish Universities",
        level: "Undergraduate",
        field: "All Fields",
        deadline: "March 2026",
        funding: "Partially Funded",
        description: "For high-calibre international students from non-EU/EEA countries",
        benefits: ["€10,000 for one year of study", "Fee waiver"],
        link: "https://www.gov.ie/en/policy-information/c0c0e7-international-education-scholarships/",
        eligibility: "Non-EU/EEA, first year of undergraduate study"
    },

    // Turkey Scholarships 2025-2027
    {
        id: 89,
        title: "Türkiye Bursları Scholarships 2026",
        country: "Turkey",
        university: "Various Turkish Universities",
        level: "Masters",
        field: "All Fields",
        deadline: "February 2026",
        funding: "Fully Funded",
        description: "Turkish government scholarships for international students",
        benefits: ["Full tuition", "Monthly stipend", "Accommodation", "Health insurance", "Turkish language course"],
        link: "https://www.turkiyeburslari.gov.tr/",
        eligibility: "Academic achievement, under age limits"
    },

    // Singapore Scholarships 2025-2027
    {
        id: 90,
        title: "Singapore International Graduate Award 2026",
        country: "Singapore",
        university: "Various Singapore Universities",
        level: "PhD",
        field: "Sciences",
        deadline: "December 2025",
        funding: "Fully Funded",
        description: "For international students to pursue PhD in science and engineering",
        benefits: ["Full tuition", "SGD 3,200 monthly stipend", "Conference allowance"],
        link: "https://www.a-star.edu.sg/Scholarships/for-graduate-studies/singapore-international-graduate-award-singa",
        eligibility: "Excellent academic record in science/engineering"
    }
];
